name: reinvent-dnc
channels:
  - pytorch
  - defaults
  - rdkit
  - openeye
dependencies:
  - python=3.6
  - rdkit=2018.09.1.0
  - pytorch=1.0
  - tqdm=4.26.0
  - nose=1.3.7
  - tensorflow-gpu
  - scipy
  - matplotlib
  - openeye-toolkits
  - pip:
    - tensorboardX
    - imageio
    - requests
    - moviepy
    - torchvision
    - deepsmiles
